import { supabase } from './supabase';
import { computeEstimateTotals } from '@br/shared';
import type {
  Estimate,
  EstimateLineItem,
  EstimateLineKind,
  EstimateStatus,
  SavedRate,
  VatMode,
  UUID,
} from '@br/shared';

/**
 * Data helpers for the Estimates (quotes) feature. Same defensive multi-query
 * pattern as invoices.ts / variations.ts — no PostgREST embeds.
 *
 * Estimates are STANDALONE: they exist before any project/client, so these
 * queries are tenant-scoped (RLS handles the owner/PM gate). A won estimate is
 * converted into a project separately (Phase 4).
 *
 * Money is integer pence. The stored subtotal/vat/total on `estimates` are
 * computed with computeEstimateTotals() at write time; the per-line
 * line_cost_pence / line_price_pence are generated by the DB.
 */

export interface EstimateListItem {
  id: UUID;
  number: string;
  title: string;
  client_name: string;
  status: EstimateStatus;
  total_pence: number;
  valid_until: string | null;
  created_at: string;
}

export async function listEstimates(): Promise<EstimateListItem[]> {
  const { data, error } = await supabase
    .from('estimates')
    .select('id, number, title, client_name, status, total_pence, valid_until, created_at')
    .order('created_at', { ascending: false });
  if (error || !data) return [];
  return data.map((r) => ({
    id: r.id,
    number: r.number,
    title: r.title,
    client_name: r.client_name,
    status: r.status,
    total_pence: Number(r.total_pence),
    valid_until: r.valid_until,
    created_at: r.created_at,
  }));
}

function normalizeLine(l: Record<string, unknown>): EstimateLineItem {
  return {
    id: l.id as string,
    estimate_id: l.estimate_id as string,
    tenant_id: l.tenant_id as string,
    saved_rate_id: (l.saved_rate_id as string | null) ?? null,
    position: Number(l.position),
    kind: l.kind as EstimateLineKind,
    description: l.description as string,
    quantity: Number(l.quantity),
    unit: l.unit as string,
    unit_cost_pence: Number(l.unit_cost_pence),
    markup_percent: Number(l.markup_percent),
    line_cost_pence: Number(l.line_cost_pence),
    line_price_pence: Number(l.line_price_pence),
    created_at: l.created_at as string,
  };
}

export interface EstimateWithLines extends Estimate {
  lines: EstimateLineItem[];
}

export async function getEstimate(id: UUID): Promise<EstimateWithLines | null> {
  const { data: row, error } = await supabase
    .from('estimates')
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error || !row) return null;
  const { data: lines } = await supabase
    .from('estimate_line_items')
    .select('*')
    .eq('estimate_id', id)
    .order('position', { ascending: true });
  return {
    ...(row as Estimate),
    cost_subtotal_pence: Number(row.cost_subtotal_pence),
    subtotal_pence: Number(row.subtotal_pence),
    vat_pence: Number(row.vat_pence),
    total_pence: Number(row.total_pence),
    lines: (lines ?? []).map(normalizeLine),
  };
}

/**
 * Next sequential estimate number for a tenant, scoped to the calendar year.
 * Format: EST-YYYY-NNN.
 */
export async function nextEstimateNumber(tenantId: UUID): Promise<string> {
  const year = new Date().getFullYear();
  const prefix = `EST-${year}-`;
  const { data } = await supabase
    .from('estimates')
    .select('number')
    .eq('tenant_id', tenantId)
    .like('number', `${prefix}%`)
    .order('number', { ascending: false })
    .limit(1);
  let nextSeq = 1;
  if (data && data[0]) {
    const match = (data[0].number as string).match(/-(\d+)$/);
    if (match) nextSeq = parseInt(match[1], 10) + 1;
  }
  return `${prefix}${nextSeq.toString().padStart(3, '0')}`;
}

export interface EstimateLineDraft {
  kind: EstimateLineKind;
  saved_rate_id: UUID | null;
  description: string;
  quantity: number;
  unit: string;
  unit_cost_pence: number;
  markup_percent: number;
}

export interface CreateEstimateInput {
  tenant_id: UUID;
  created_by: UUID;
  title: string;
  project_type: string | null;
  client_name: string;
  client_email: string | null;
  client_phone: string | null;
  site_address_line1: string | null;
  site_address_line2: string | null;
  city: string | null;
  postcode: string | null;
  vat_mode: VatMode;
  vat_rate_bp: number;
  valid_until: string | null;
  notes: string | null;
  terms: string | null;
  lines: EstimateLineDraft[];
  /** Override auto-numbering if the builder keeps their own sequence. */
  number_override?: string | null;
}

export async function createEstimate(input: CreateEstimateInput): Promise<UUID> {
  const totals = computeEstimateTotals(input.lines, input.vat_mode, input.vat_rate_bp);

  // Retry on number collision (two quotes created in the same second).
  for (let attempt = 0; attempt < 3; attempt++) {
    const number =
      input.number_override ?? (await nextEstimateNumber(input.tenant_id));
    const { data: est, error } = await supabase
      .from('estimates')
      .insert({
        tenant_id: input.tenant_id,
        created_by: input.created_by,
        number,
        title: input.title,
        project_type: input.project_type ?? null,
        client_name: input.client_name,
        client_email: input.client_email,
        client_phone: input.client_phone,
        site_address_line1: input.site_address_line1,
        site_address_line2: input.site_address_line2,
        city: input.city,
        postcode: input.postcode,
        status: 'draft' as EstimateStatus,
        vat_mode: input.vat_mode,
        vat_rate_bp: input.vat_rate_bp,
        cost_subtotal_pence: totals.cost_subtotal_pence,
        subtotal_pence: totals.subtotal_pence,
        vat_pence: totals.vat_pence,
        total_pence: totals.total_pence,
        valid_until: input.valid_until,
        notes: input.notes,
        terms: input.terms,
      })
      .select('id')
      .single();

    if (error) {
      if (error.code === '23505' && !input.number_override) continue;
      throw new Error(error.message);
    }

    const estimateId = est.id as string;
    if (input.lines.length > 0) {
      const rows = input.lines.map((l, i) => ({
        estimate_id: estimateId,
        tenant_id: input.tenant_id,
        saved_rate_id: l.saved_rate_id,
        position: i,
        kind: l.kind,
        description: l.description,
        quantity: l.quantity,
        unit: l.unit,
        unit_cost_pence: l.unit_cost_pence,
        markup_percent: l.markup_percent,
      }));
      const { error: lineErr } = await supabase
        .from('estimate_line_items')
        .insert(rows);
      if (lineErr) throw new Error(lineErr.message);
    }
    return estimateId;
  }
  throw new Error('Could not pick a unique estimate number. Try again.');
}

export interface UpdateEstimateInput extends CreateEstimateInput {
  id: UUID;
}

/**
 * Replace-in-place update for a draft: rewrites header fields + totals and
 * swaps the full set of line items. Only meant for estimates still in 'draft'.
 */
export async function updateEstimate(input: UpdateEstimateInput): Promise<void> {
  const totals = computeEstimateTotals(input.lines, input.vat_mode, input.vat_rate_bp);
  const { error } = await supabase
    .from('estimates')
    .update({
      title: input.title,
      project_type: input.project_type ?? null,
      client_name: input.client_name,
      client_email: input.client_email,
      client_phone: input.client_phone,
      site_address_line1: input.site_address_line1,
      site_address_line2: input.site_address_line2,
      city: input.city,
      postcode: input.postcode,
      vat_mode: input.vat_mode,
      vat_rate_bp: input.vat_rate_bp,
      cost_subtotal_pence: totals.cost_subtotal_pence,
      subtotal_pence: totals.subtotal_pence,
      vat_pence: totals.vat_pence,
      total_pence: totals.total_pence,
      valid_until: input.valid_until,
      notes: input.notes,
      terms: input.terms,
    })
    .eq('id', input.id);
  if (error) throw new Error(error.message);

  // Swap the line items wholesale (simplest correct approach for a draft).
  const { error: delErr } = await supabase
    .from('estimate_line_items')
    .delete()
    .eq('estimate_id', input.id);
  if (delErr) throw new Error(delErr.message);

  if (input.lines.length > 0) {
    const rows = input.lines.map((l, i) => ({
      estimate_id: input.id,
      tenant_id: input.tenant_id,
      saved_rate_id: l.saved_rate_id,
      position: i,
      kind: l.kind,
      description: l.description,
      quantity: l.quantity,
      unit: l.unit,
      unit_cost_pence: l.unit_cost_pence,
      markup_percent: l.markup_percent,
    }));
    const { error: insErr } = await supabase
      .from('estimate_line_items')
      .insert(rows);
    if (insErr) throw new Error(insErr.message);
  }
}

export async function deleteEstimate(id: UUID): Promise<void> {
  const { error } = await supabase.from('estimates').delete().eq('id', id);
  if (error) throw new Error(error.message);
}

// --- sending (mobile: generate the shareable link + mark sent) -------------
// The web admin additionally renders a branded PDF and emails the client;
// on mobile we generate the same tokenised link so the builder can share it
// on site (WhatsApp / text) straight away. The public page renders from the
// token either way.
const PUBLIC_APP_URL = 'https://buildersready.uk';

function makeAcceptToken(): string {
  try {
    const g = (
      globalThis as unknown as {
        crypto?: { getRandomValues?: (a: Uint8Array) => Uint8Array };
      }
    ).crypto;
    if (g && typeof g.getRandomValues === 'function') {
      const arr = new Uint8Array(24);
      g.getRandomValues(arr);
      return Array.from(arr, (b) => b.toString(16).padStart(2, '0')).join('');
    }
  } catch {
    /* fall through to Math.random */
  }
  let t = '';
  for (let i = 0; i < 48; i++) t += Math.floor(Math.random() * 36).toString(36);
  return t + Date.now().toString(36);
}

export interface SendEstimateResult {
  token: string;
  url: string;
}

/**
 * Mark a quote as sent and return its shareable link. Reuses an existing
 * token so links stay stable across re-shares. Never touches an already
 * accepted quote (guard in the UI too).
 */
export async function sendEstimate(
  id: UUID,
  existingToken: string | null,
): Promise<SendEstimateResult> {
  const token = existingToken ?? makeAcceptToken();
  const { error } = await supabase
    .from('estimates')
    .update({
      status: 'sent',
      sent_at: new Date().toISOString(),
      accept_token: token,
    })
    .eq('id', id);
  if (error) throw new Error(error.message);
  return { token, url: `${PUBLIC_APP_URL}/q/${token}` };
}

// --- saved rate library ----------------------------------------------------

export async function listSavedRates(): Promise<SavedRate[]> {
  const { data, error } = await supabase
    .from('saved_rates')
    .select('*')
    .eq('active', true)
    .order('position', { ascending: true });
  if (error || !data) return [];
  return data.map((r) => ({
    id: r.id,
    tenant_id: r.tenant_id,
    kind: r.kind,
    description: r.description,
    unit: r.unit,
    default_unit_cost_pence: Number(r.default_unit_cost_pence),
    default_markup_percent: Number(r.default_markup_percent),
    position: Number(r.position),
    active: r.active,
    created_at: r.created_at,
    updated_at: r.updated_at,
  }));
}

export interface CreateSavedRateInput {
  tenant_id: UUID;
  kind: EstimateLineKind;
  description: string;
  unit: string;
  default_unit_cost_pence: number;
  default_markup_percent: number;
}

export async function createSavedRate(input: CreateSavedRateInput): Promise<UUID> {
  const { data, error } = await supabase
    .from('saved_rates')
    .insert({
      tenant_id: input.tenant_id,
      kind: input.kind,
      description: input.description,
      unit: input.unit,
      default_unit_cost_pence: input.default_unit_cost_pence,
      default_markup_percent: input.default_markup_percent,
    })
    .select('id')
    .single();
  if (error || !data) throw new Error(error?.message ?? 'Failed to save rate.');
  return data.id as string;
}

export interface UpdateSavedRateInput extends CreateSavedRateInput {
  id: UUID;
}

export async function updateSavedRate(input: UpdateSavedRateInput): Promise<void> {
  const { error } = await supabase
    .from('saved_rates')
    .update({
      kind: input.kind,
      description: input.description,
      unit: input.unit,
      default_unit_cost_pence: input.default_unit_cost_pence,
      default_markup_percent: input.default_markup_percent,
    })
    .eq('id', input.id);
  if (error) throw new Error(error.message);
}

export async function deleteSavedRate(id: UUID): Promise<void> {
  const { error } = await supabase.from('saved_rates').delete().eq('id', id);
  if (error) throw new Error(error.message);
}

/** Duplicate a quote into a fresh draft. Returns the new estimate id. */
export async function duplicateEstimate(
  id: UUID,
  tenantId: UUID,
  createdBy: UUID,
): Promise<UUID> {
  const src = await getEstimate(id);
  if (!src) throw new Error('Quote not found.');
  return createEstimate({
    tenant_id: tenantId,
    created_by: createdBy,
    title: `${src.title} (copy)`,
    project_type: src.project_type,
    client_name: src.client_name,
    client_email: src.client_email,
    client_phone: src.client_phone,
    site_address_line1: src.site_address_line1,
    site_address_line2: src.site_address_line2,
    city: src.city,
    postcode: src.postcode,
    vat_mode: src.vat_mode,
    vat_rate_bp: src.vat_rate_bp,
    valid_until: src.valid_until,
    notes: src.notes,
    terms: src.terms,
    lines: src.lines.map((l) => ({
      kind: l.kind,
      saved_rate_id: l.saved_rate_id,
      description: l.description,
      quantity: l.quantity,
      unit: l.unit,
      unit_cost_pence: l.unit_cost_pence,
      markup_percent: l.markup_percent,
    })),
  });
}
